language: generic
sudo: required
services:
  - docker

before_install:
  - docker build  -t shubhamjain2908/docker-travis-ci-demo -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shubhamjain2908/docker-travis-ci-demo npm run test

after_success:
  - docker build -t shubhamjain2908/multi-client ./client
  - docker build -t shubhamjain2908/multi-nginx ./nginx
  - docker build -t shubhamjain2908/multi-server ./server
  - docker build -t shubhamjain2908/multi-worker ./worker
  # Log in to the docker CLI (echoing the password & passing it to the next command)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images & push to docker HUB
  - docker push shubhamjain2908/multi-client
  - docker push shubhamjain2908/multi-nginx
  - docker push shubhamjain2908/multi-server
  - docker push shubhamjain2908/multi-worker
